version: 0.0
os: linux
files:
  - source: systemd/app.service
    destination: /etc/systemd/system
  - source: src
    destination: /home/app
  - source: nginx.conf
    destination: /etc/nginx
  - source: requirements.txt
    destination: /home/app
  - source: fluent-bit.conf
    destination: /etc/fluent-bit
  - source: systemd/journald.conf
    destination: /etc/systemd
  - source: web
    destination: /home/proxy/web
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/create_users.sh
    - location: scripts/stop_services.sh
    - location: scripts/setup_env_var.sh
  AfterInstall:
    - location: scripts/init_venv.sh
    - location: scripts/restart_journald.sh
    - location: scripts/set_fluent_bit_env.sh
    - location: scripts/start_services.sh
  ValidateService:
    - location: scripts/test_proxy.sh
    #- location: scripts/test_elb_health.py